name: Compile and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create executable
        id: create_exe
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'src/main.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'cfmd'
          options: --onefile, --name "cfmd", --windowed, 
      
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: Release ${{ github.ref }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cfmd
          asset_name: cfmd
          asset_content_type: application/octet-stream
        env:
          GITHUB_TOKEN: ${{ github.token }}

            