name: Compile and Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          spec: 'src/main.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'cfmd'
          options: --onefile, --name "Curseforge minecraft modpack downloader", --windowed, 

      - name: Create Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cfmd
          asset_name: cfmd
          asset_content_type: application/octet-stream

            