name: Compile and Release
on:
  push:
    branches:
      - [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create executable
        uses: sayyid5416/pyinstaller@v1
        with:
          python_ver: '3.6'
          spec: 'src/main.py'
          requirements: 'src/requirements.txt'
          upload_exe_with_name: 'cfmpdl'
          options: --onefile, --name "CurseForge Modpack Downloader", --windowed, 

      - name: Create Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: dist/cfmpdl
          asset_name: cfmpdl
          asset_content_type: application/octet-stream

            